### ISSUE TITLE
kaffpa segmentation fault in single_kway_refinement_round_internal

### ISSUE THREAD

**Issue by jlabeit** [KaHIP/KaHIP#57]
**Bug description**
For some small input graphs and `k=2` `kaffpa` crashes with a segmentation fault during partitioning. 

I am not sure what the best way is to debug this issue: Is there an easy way to compile the kaffpa with optimizations disabled and debug symbols?

**Steps to reproduce**
Command run:
```
kaffpa input.metis --k=2 --preconfiguration=strong --output_filename=output.partition
```

With the metis input file
```
10 45 1
2 0 3 0 4 0 5 0 6 0 7 0 8 0 9 0 10 0
1 0 3 0 4 0 5 0 6 0 7 0 8 0 9 0 10 0
1 0 2 0 4 0 5 0 6 0 7 0 8 0 9 0 10 0
1 0 2 0 3 0 5 0 6 0 7 0 8 0 9 0 10 0
1 0 2 0 3 0 4 0 6 0 7 0 8 0 9 0 10 0
1 0 2 0 3 0 4 0 5 0 7 0 8 0 9 0 10 0
1 0 2 0 3 0 4 0 5 0 6 0 8 0 9 0 10 0
1 0 2 0 3 0 4 0 5 0 6 0 7 0 9 0 10 0
1 0 2 0 3 0 4 0 5 0 6 0 7 0 8 0 10 0
1 0 2 0 3 0 4 0 5 0 6 0 7 0 8 0 9 0
```

Stack strace:
```
0x00005555555d67bf in kway_graph_refinement_core::single_kway_refinement_round_internal(PartitionConfig&, graph_access&, complete_boundary&, std::vector<unsigned int, std::allocator<unsigned int> >&, int, std::unordered_map<unsigned int const, moved_index, hash_nodes, compare_nodes, std::allocator<std::pair<unsigned int const, moved_index> > >&, bool, std::unordered_map<unsigned int, unsigned int, std::hash<unsigned int>, std::equal_to<unsigned int>, std::allocator<std::pair<unsigned int const, unsigned int> > >&) ()
(gdb) bt
#0  0x00005555555d67bf in kway_graph_refinement_core::single_kway_refinement_round_internal(PartitionConfig&, graph_access&, complete_boundary&, std::vector<unsigned int, std::allocator<unsigned int> >&, int, std::unordered_map<unsigned int const, moved_index, hash_nodes, compare_nodes, std::allocator<std::pair<unsigned int const, moved_index> > >&, bool, std::unordered_map<unsigned int, unsigned int, std::hash<unsigned int>, std::equal_to<unsigned int>, std::allocator<std::pair<unsigned int const, unsigned int> > >&) ()
#1  0x00005555555d7429 in kway_graph_refinement_core::single_kway_refinement_round(PartitionConfig&, graph_access&, complete_boundary&, std::vector<unsigned int, std::allocator<unsigned int> >&, int, std::unordered_map<unsigned int const, moved_index, hash_nodes, compare_nodes, std::allocator<std::pair<unsigned int const, moved_index> > >&) ()
#2  0x00005555555d5501 in kway_graph_refinement::perform_refinement(PartitionConfig&, graph_access&, complete_boundary&) ()
#3  0x00005555555c0daf in mixed_refinement::perform_refinement(PartitionConfig&, graph_access&, complete_boundary&) ()
#4  0x00005555555886f6 in wcycle_partitioner::perform_partitioning_recursive(PartitionConfig&, graph_access&, complete_boundary**) ()
#5  0x000055555558ad00 in wcycle_partitioner::perform_partitioning(PartitionConfig const&, graph_access&) ()
#6  0x00005555555833b7 in graph_partitioner::single_run(PartitionConfig&, graph_access&) ()
#7  0x0000555555584639 in graph_partitioner::perform_partitioning(PartitionConfig&, graph_access&) ()
```

Version: Could be reproduced with both `v2.12` current master `v3.00`.

**Comment by schulzchristian** [comment]
I dont think zero weight edges are supported. Could you check if this is
the problem?

Best
Christian

**Comment by schulzchristian** [comment]
I just checked it, the zero weight edges should be the problem.

**Comment by schulzchristian** [comment]
@jlabeit, I assume that this is a small example graph? If you have problems in your application with zero weight edges, I suggest just removing them from the graph as they will not contribute to the objective of the problem. Let me know if that works for you.

**Comment by jlabeit** [comment]
@schulzchristian Thanks for the quick response. Yes, the problem was with the zero weighted edges. After removing them from all my instances everything works as expected.
